# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ultra.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ultra.proto',
  package='ultraTrackingService',
  syntax='proto3',
  serialized_options=b'\252\002\024ultraTrackingService',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0bultra.proto\x12\x14ultraTrackingService\"\xc1\x01\n\rVTByteRequest\x12\x11\n\tImageData\x18\x01 \x01(\x0c\x12\x11\n\ttimeStamp\x18\x02 \x01(\t\x12\x10\n\x08\x63\x61meraID\x18\x03 \x01(\t\x12\x0e\n\x06Matrix\x18\x04 \x01(\t\x12\x0e\n\x06Refine\x18\x05 \x01(\t\x12\r\n\x05\x43\x61lib\x18\x06 \x01(\t\x12\x12\n\nAccumulate\x18\x07 \x01(\t\x12\x10\n\x08\x42ounding\x18\x08 \x01(\t\x12\x11\n\tStabilize\x18\t \x01(\t\x12\x10\n\x08SaveData\x18\n \x01(\t\"\x9a\x01\n\x08PoseData\x12\x0e\n\x06USData\x18\x01 \x01(\x0c\x12\x0f\n\x07VolData\x18\x02 \x01(\x0c\x12\x0f\n\x07PoseMat\x18\x03 \x01(\t\x12\x10\n\x08\x43\x61libMat\x18\x04 \x01(\t\x12\x11\n\tAnchorMat\x18\x05 \x01(\t\x12\x0f\n\x07MiscMsg\x18\x06 \x01(\t\x12\x13\n\x0bRenderFrame\x18\x07 \x01(\t\x12\x11\n\tRenderVol\x18\x08 \x01(\t2\xb7\x01\n\tVTService\x12[\n\x10StreamBytesVideo\x12#.ultraTrackingService.VTByteRequest\x1a\x1e.ultraTrackingService.PoseData(\x01\x30\x01\x12M\n\x06OneWay\x12#.ultraTrackingService.VTByteRequest\x1a\x1e.ultraTrackingService.PoseDataB\x17\xaa\x02\x14ultraTrackingServiceb\x06proto3'
)




_VTBYTEREQUEST = _descriptor.Descriptor(
  name='VTByteRequest',
  full_name='ultraTrackingService.VTByteRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ImageData', full_name='ultraTrackingService.VTByteRequest.ImageData', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='timeStamp', full_name='ultraTrackingService.VTByteRequest.timeStamp', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cameraID', full_name='ultraTrackingService.VTByteRequest.cameraID', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Matrix', full_name='ultraTrackingService.VTByteRequest.Matrix', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Refine', full_name='ultraTrackingService.VTByteRequest.Refine', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Calib', full_name='ultraTrackingService.VTByteRequest.Calib', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Accumulate', full_name='ultraTrackingService.VTByteRequest.Accumulate', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Bounding', full_name='ultraTrackingService.VTByteRequest.Bounding', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Stabilize', full_name='ultraTrackingService.VTByteRequest.Stabilize', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='SaveData', full_name='ultraTrackingService.VTByteRequest.SaveData', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=38,
  serialized_end=231,
)


_POSEDATA = _descriptor.Descriptor(
  name='PoseData',
  full_name='ultraTrackingService.PoseData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='USData', full_name='ultraTrackingService.PoseData.USData', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='VolData', full_name='ultraTrackingService.PoseData.VolData', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='PoseMat', full_name='ultraTrackingService.PoseData.PoseMat', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='CalibMat', full_name='ultraTrackingService.PoseData.CalibMat', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='AnchorMat', full_name='ultraTrackingService.PoseData.AnchorMat', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='MiscMsg', full_name='ultraTrackingService.PoseData.MiscMsg', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='RenderFrame', full_name='ultraTrackingService.PoseData.RenderFrame', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='RenderVol', full_name='ultraTrackingService.PoseData.RenderVol', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=234,
  serialized_end=388,
)

DESCRIPTOR.message_types_by_name['VTByteRequest'] = _VTBYTEREQUEST
DESCRIPTOR.message_types_by_name['PoseData'] = _POSEDATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

VTByteRequest = _reflection.GeneratedProtocolMessageType('VTByteRequest', (_message.Message,), {
  'DESCRIPTOR' : _VTBYTEREQUEST,
  '__module__' : 'ultra_pb2'
  # @@protoc_insertion_point(class_scope:ultraTrackingService.VTByteRequest)
  })
_sym_db.RegisterMessage(VTByteRequest)

PoseData = _reflection.GeneratedProtocolMessageType('PoseData', (_message.Message,), {
  'DESCRIPTOR' : _POSEDATA,
  '__module__' : 'ultra_pb2'
  # @@protoc_insertion_point(class_scope:ultraTrackingService.PoseData)
  })
_sym_db.RegisterMessage(PoseData)


DESCRIPTOR._options = None

_VTSERVICE = _descriptor.ServiceDescriptor(
  name='VTService',
  full_name='ultraTrackingService.VTService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=391,
  serialized_end=574,
  methods=[
  _descriptor.MethodDescriptor(
    name='StreamBytesVideo',
    full_name='ultraTrackingService.VTService.StreamBytesVideo',
    index=0,
    containing_service=None,
    input_type=_VTBYTEREQUEST,
    output_type=_POSEDATA,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='OneWay',
    full_name='ultraTrackingService.VTService.OneWay',
    index=1,
    containing_service=None,
    input_type=_VTBYTEREQUEST,
    output_type=_POSEDATA,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_VTSERVICE)

DESCRIPTOR.services_by_name['VTService'] = _VTSERVICE

# @@protoc_insertion_point(module_scope)
