# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import ultra_pb2 as ultra__pb2


class VTServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamBytesVideo = channel.stream_stream(
                '/ultraTrackingService.VTService/StreamBytesVideo',
                request_serializer=ultra__pb2.VTByteRequest.SerializeToString,
                response_deserializer=ultra__pb2.PoseData.FromString,
                )
        self.OneWay = channel.unary_unary(
                '/ultraTrackingService.VTService/OneWay',
                request_serializer=ultra__pb2.VTByteRequest.SerializeToString,
                response_deserializer=ultra__pb2.PoseData.FromString,
                )


class VTServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StreamBytesVideo(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OneWay(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VTServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamBytesVideo': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamBytesVideo,
                    request_deserializer=ultra__pb2.VTByteRequest.FromString,
                    response_serializer=ultra__pb2.PoseData.SerializeToString,
            ),
            'OneWay': grpc.unary_unary_rpc_method_handler(
                    servicer.OneWay,
                    request_deserializer=ultra__pb2.VTByteRequest.FromString,
                    response_serializer=ultra__pb2.PoseData.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ultraTrackingService.VTService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class VTService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StreamBytesVideo(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/ultraTrackingService.VTService/StreamBytesVideo',
            ultra__pb2.VTByteRequest.SerializeToString,
            ultra__pb2.PoseData.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def OneWay(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ultraTrackingService.VTService/OneWay',
            ultra__pb2.VTByteRequest.SerializeToString,
            ultra__pb2.PoseData.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
